<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" ignored="0" total="8" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
    <line>
      <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
    </line>
  </reporter-output>
  <suite name="Group of group Suite" duration-ms="59045" started-at="2021-05-22T15:44:51 SGT" finished-at="2021-05-22T15:45:50 SGT">
    <groups>
    </groups>
    <test name="Group of group Test" duration-ms="59045" started-at="2021-05-22T15:44:51 SGT" finished-at="2021-05-22T15:45:50 SGT">
      <class name="com.planit.application.tests.TC003">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.planit.application.tests.TC003@631330c]" name="beforeClass" is-config="true" duration-ms="1341" started-at="2021-05-22T15:45:32 SGT" finished-at="2021-05-22T15:45:33 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC003@631330c]" name="testcase" duration-ms="7719" started-at="2021-05-22T15:45:33 SGT" data-provider="testData" finished-at="2021-05-22T15:45:41 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{item2=Fluffy Bunny=1, item1=Funny Cow=2}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToShoppingPage(HomePage.java:47)
at com.planit.application.tests.TC003.testcase(TC003.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.planit.application.tests.TC003@631330c]" name="afterClass" is-config="true" duration-ms="45" started-at="2021-05-22T15:45:41 SGT" finished-at="2021-05-22T15:45:41 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.planit.application.tests.TC003 -->
      <class name="com.planit.application.tests.TC004">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.planit.application.tests.TC004@42f93a98]" name="beforeClass" is-config="true" duration-ms="1270" started-at="2021-05-22T15:45:41 SGT" finished-at="2021-05-22T15:45:42 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC004@42f93a98]" name="testcase" duration-ms="7627" started-at="2021-05-22T15:45:42 SGT" data-provider="testData" finished-at="2021-05-22T15:45:50 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{item2=Fluffy Bunny=5, item1=Stuffed Frog=2, item3=Valentine Bear=3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToShoppingPage(HomePage.java:47)
at com.planit.application.tests.TC004.testcase(TC004.java:43)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.planit.application.tests.TC004@42f93a98]" name="afterClass" is-config="true" duration-ms="46" started-at="2021-05-22T15:45:50 SGT" finished-at="2021-05-22T15:45:50 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.planit.application.tests.TC004 -->
      <class name="com.planit.application.tests.TC001">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.planit.application.tests.TC001@7e2d773b]" name="beforeClass" is-config="true" duration-ms="2170" started-at="2021-05-22T15:44:51 SGT" finished-at="2021-05-22T15:44:53 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC001@7e2d773b]" name="testcase" duration-ms="7727" started-at="2021-05-22T15:44:54 SGT" data-provider="testData" finished-at="2021-05-22T15:45:02 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Vaibhav, message=this application is nice., email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC001.testcase(TC001.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.planit.application.tests.TC001@7e2d773b]" name="afterClass" is-config="true" duration-ms="57" started-at="2021-05-22T15:45:02 SGT" finished-at="2021-05-22T15:45:02 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.planit.application.tests.TC001 -->
      <class name="com.planit.application.tests.TC002">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="beforeClass" is-config="true" duration-ms="1270" started-at="2021-05-22T15:45:02 SGT" finished-at="2021-05-22T15:45:03 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="testcase" duration-ms="7608" started-at="2021-05-22T15:45:03 SGT" data-provider="testData" finished-at="2021-05-22T15:45:11 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Vaibhav, message=Sending message 1, email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC002.testcase(TC002.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="testcase" duration-ms="5208" started-at="2021-05-22T15:45:11 SGT" data-provider="testData" finished-at="2021-05-22T15:45:16 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Jay, message=Sending message 2, email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC002.testcase(TC002.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="testcase" duration-ms="5186" started-at="2021-05-22T15:45:16 SGT" data-provider="testData" finished-at="2021-05-22T15:45:21 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Sniti, message=Sending message 3, email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC002.testcase(TC002.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="testcase" duration-ms="5208" started-at="2021-05-22T15:45:21 SGT" data-provider="testData" finished-at="2021-05-22T15:45:26 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Amruta, message=Sending message 4, email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC002.testcase(TC002.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.util.Map)[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="testcase" duration-ms="5238" started-at="2021-05-22T15:45:26 SGT" data-provider="testData" finished-at="2021-05-22T15:45:32 SGT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{forename=Abir, message=Sending message 5, email=vaibhav.kavimandan@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Error Occured while clicking on ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Error Occured while clicking on 
at org.testng.Assert.fail(Assert.java:99)
at com.planit.core.framework.BaseUtil.clickOn(BaseUtil.java:24)
at com.planit.application.pagefactory.HomePage.goToContactPage(HomePage.java:51)
at com.planit.application.tests.TC002.testcase(TC002.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Base Url: https://jupiter.cloud.planittesting.com launched Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.planit.application.tests.TC002@2353b3e6]" name="afterClass" is-config="true" duration-ms="190" started-at="2021-05-22T15:45:32 SGT" finished-at="2021-05-22T15:45:32 SGT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.planit.application.tests.TC002 -->
    </test> <!-- Group of group Test -->
  </suite> <!-- Group of group Suite -->
</testng-results>
